#!/usr/bin/env bash

if [ $# -lt 1 ] # number of input parameters less than 2
then
  echo -ne "Remote branch name: "
  read name
  git checkout --track -b $name origin/$name
else
  git checkout --track -b $2 origin/$2
fi