#! /usr/bin/env bash

if [ $# -lt 2 ] # number of input parameters less than 2
then
  echo -ne "Commit message: "
  read message
  git commit -a -n -m "NEW: $message"
else
  git commit -a -n -m "NEW: $2"
fi